version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lyrox-postgres
    environment:
      POSTGRES_USER: lyrox
      POSTGRES_PASSWORD: lyrox_dev
      POSTGRES_DB: lyrox_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lyrox"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: lyrox-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: lyrox
      MONGO_INITDB_ROOT_PASSWORD: lyrox_dev
      MONGO_INITDB_DATABASE: lyrox_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lyrox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
  redis_data:
